services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-2fa-app

    ports:
      - "8080:8080"

    volumes:
      - seed-data:/data
      - cron-output:/cron

    environment:
      TZ: UTC

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
